/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'Index copy': typeof import('./src/components/top-category/index copy.vue')['default']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutOverlay: typeof import('@nutui/nutui-taro')['Overlay']
    NutSticky: typeof import('@nutui/nutui-taro')['Sticky']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    TopCategory: typeof import('./src/components/top-category/index.vue')['default']
    TopSearch: typeof import('./src/components/top-search/index.vue')['default']
  }
}
